name: ContainerUtils
version: 1.0.0
main: org.garsooon.containerutils.ContainerUtils
api-version: 1.0
description: Restocks containers with their original items on a timer or command
author: Garsooon
website: https://github.com/Garsooon/ContainerUtils

commands:
  restock:
    description: ContainerRestock management commands
    usage: /restock [create|list|clear|time|ctime|reload]
    permission: containerutils.admin
    aliases: [cr, crest]

permissions:
  containerutils.admin:
    description: Allows access to all ContainerRestock commands
    default: op
